# Generated by Django 6.0.2 on 2026-03-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.ImageField(null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(null=True, upload_to='room_images/'),
        ),
    ]
