# Generated by Django 6.0.2 on 2026-03-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField()),
                ('Number_of_beds', models.IntegerField()),
                ('Total_price', models.IntegerField()),
                ('Username', models.CharField(blank=True, max_length=50, null=True)),
                ('share', models.IntegerField()),
                ('hostel_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
