# Generated by Django 6.0.2 on 2026-03-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_remove_book_details_username_book_details_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_details',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
